language: go
go: 
 - 1.2

addons:
  postgresql: "9.3"

before_script:  
  - psql -c 'create database goauthserv;' -U postgres
  - psql -c "create user goauthserv with password 'goauthserv'" -U postgres
  - psql -c "grant all privileges on database goauthserv to goauthserv" -U postgres
  
script:
 - go test -v ./...